// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlfHkQKOLhXsYV6JI2wjKrBibl_lTwBo',
    appId: '1:230569510508:web:c513aaec0ef3eae382fa49',
    messagingSenderId: '230569510508',
    projectId: 'cleannow-8281c',
    authDomain: 'cleannow-8281c.firebaseapp.com',
    storageBucket: 'cleannow-8281c.firebasestorage.app',
    measurementId: 'G-KWLFHQ764W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfvA8ZoKG_pNgGsyomeM6rqZagP3Oju4',
    appId: '1:230569510508:android:117ebf5be4f1a6de82fa49',
    messagingSenderId: '230569510508',
    projectId: 'cleannow-8281c',
    storageBucket: 'cleannow-8281c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqiXljKNJ9LQehjF0SVpRgENhZmWwBqQ',
    appId: '1:230569510508:ios:e3e2c495a0f189c882fa49',
    messagingSenderId: '230569510508',
    projectId: 'cleannow-8281c',
    storageBucket: 'cleannow-8281c.firebasestorage.app',
    iosClientId: '230569510508-mhok7ngeln85njrqderpucb3nbe8vu43.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBlfHkQKOLhXsYV6JI2wjKrBibl_lTwBo',
    appId: '1:230569510508:web:2f79d8d3e5a9ba6782fa49',
    messagingSenderId: '230569510508',
    projectId: 'cleannow-8281c',
    authDomain: 'cleannow-8281c.firebaseapp.com',
    storageBucket: 'cleannow-8281c.firebasestorage.app',
    measurementId: 'G-Z7MN527E88',
  );
}
