import 'dart:async';
import 'package:flutter/material.dart';
import 'dart:convert';
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:intl/intl.dart';
import 'package:image_picker/image_picker.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:provider/provider.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../app/route_names.dart';
import '../core/constants.dart';
import '../core/file_download.dart';
import '../core/utils.dart';
import '../core/widgets.dart';
import '../data/models/models.dart';
import '../data/providers/app_providers.dart';
import '../data/remote/clean_now_api.dart';

part 'screens/splash_screen.dart';
part 'screens/onboarding_screen.dart';
part 'screens/login_screen.dart';
part 'screens/register_screen.dart';
part 'screens/cleaner_application_screen.dart';
part 'screens/unauthorized_screen.dart';
part 'screens/forgot_password_screen.dart';
part 'screens/shell_home_screens.dart';
part 'screens/admin_dashboard_screen.dart';
part 'screens/cleaner_screens.dart';
part 'screens/admin_customer_screens.dart';
part 'screens/admin_cleaner_management_screen.dart';
part 'screens/admin_operations_screens.dart';
part 'screens/service_screens.dart';
part 'screens/booking_screens.dart';
part 'screens/customer_screens.dart';
part 'screens/shared_screen_widgets.dart';
